service: import-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 's3:listBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ImportS3Bucket
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ImportS3Bucket
            - '/*'
    - Effect: 'Allow'
      Action: 's3:PutBucketNotification'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ImportS3Bucket
  environment:
    bucketName: rc-import-service-bucket

resources:
  Resources:
    ## Specifying the S3 Bucket
    ImportS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.bucketName}
        AccessControl: PublicRead
        VersioningConfiguration:
          Status: Enabled
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
              - "PUT"
              AllowedOrigins: 
              - "*"
              AllowedHeaders:
              - "*"



functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: ${self:provider.environment.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: "uploaded/"
          existing: true
  